- hosts: all
  connection: local
  become: yes
  become_user: root
  pre_tasks:
    - name: "[pre task] apt cache update"
      apt: update_cache=yes cache_valid_time=86400
  roles:
    - common
    - mysql
    - nodejs
